import { useState } from "react";
import { motion } from "framer-motion";

export default function Home() {
      const [form, setForm] = useState({ name: "", contact: "", password: "" });

        const handleChange = (e) => {
                setForm({ ...form, [e.target.name]: e.target.value });
        };

          const handleSubmit = (e) => {
                e.preventDefault();
                    alert(`Signup submitted for ${form.name}`);
          };

            return (
                    <div className="min-h-screen bg-white text-slate-900 px-4 py-6">
                          <header className="flex items-center justify-between max-w-5xl mx-auto">
                                  <div className="flex items-center gap-3">
                                            <div className="w-10 h-10 flex items-center justify-center bg-gradient-to-br from-slate-800 to-emerald-600 text-white font-bold rounded-lg">
                                                        TZ
                                                                  </div>
                                                                            <div>
                                                                                        <h1 className="text-xl font-bold">TradeZone</h1>
                                                                                                    <p className="text-slate-500 text-sm">Connect. Trade. Grow.</p>
                                                                                                              </div>
                                                                                                                      </div>
                                                                                                                            </header>

                                                                                                                                  <main className="max-w-5xl mx-auto mt-8 space-y-16">
                                                                                                                                          <motion.section className="bg-slate-50 p-6 rounded-2xl">
                                                                                                                                                    <h2 className="text-2xl font-semibold">Fast, lightweight agri-commerce</h2>
                                                                                                                                                              <p className="text-slate-600 mt-2">
                                                                                                                                                                          Post produce, search listings, message sellers, and meet via Google Maps — built for mobile users.
                                                                                                                                                                                    </p>
                                                                                                                                                                                            </motion.section>

                                                                                                                                                                                                    <motion.section>
                                                                                                                                                                                                              <h3 className="text-xl font-semibold mb-3">Create your TradeZone account</h3>
                                                                                                                                                                                                                        <form onSubmit={handleSubmit} className="grid gap-3 max-w-md">
                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                  type="text"
                                                                                                                                                                                                                                                                name="name"
                                                                                                                                                                                                                                                                              placeholder="Full name"
                                                                                                                                                                                                                                                                                            className="border border-slate-200 p-2 rounded-lg"
                                                                                                                                                                                                                                                                                                          value={form.name}
                                                                                                                                                                                                                                                                                                                        onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                            type="text"
                                                                                                                                                                                                                                                                                                                                                                                          name="contact"
                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Contact number"
                                                                                                                                                                                                                                                                                                                                                                                                                      className="border border-slate-200 p-2 rounded-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                    value={form.contact}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Create password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="border border-slate-200 p-2 rounded-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={form.password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={handleChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button type="submit" className="bg-emerald-600 text-white py-2 rounded-lg font-medium hover:bg-emerald-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Create Account
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </motion.section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
            );
}
            )
          }
        }
}